info:
  app:
    version: @project.version@
    # The configuration from the config server takes precedence over local configuration!
    description: "Can i override the description?"

    # This property is not served by the config server. So this "local" property will be picked up!
    anotherDescription: "Make Jar not War!"

# Expose all Spring Boot Actuator endpoints
endpoints:
  sensitive: false