server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
          # if searchLocations is not specified the default value of the searchLocations is identical to a local
          # Spring Boot application (so [classpath:/, classpath:/config, file:./, file:./config]).
          # This does not expose the application.properties from the server to all clients because any property sources
          # present in the server are removed before being sent to the client.
          # searchLocations: 'classpath:/, classpath:/config, file:./, file:./config'